name: Node.js CI

on: 
  push: 
    branches: 
      - main
  
  pull_request:
    branches:
      - main 


jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies and build app
        run: npm ci
      - run: npm run build
    